[package]
name = "jogo_de_advinhacao"
version = "0.1.0"
edition = "2021"
authors = ["Marcello Ale <https://github.com/marcelloale>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rand = "0.4.0"